version: '3'
services:
  comfyui:
    image: yourusername/comfyui:latest
    container_name: comfyui
    runtime: nvidia
    ports:
      - "8188:8188"
    volumes:
      - ./models:/app/models                  # Mount models directory
      - ./output:/app/output                  # Mount output directory
      - ./temp:/app/temp                      # Mount temp directory
      - ./custom_nodes:/app/custom_nodes      # Mount custom nodes
    environment:
      - NVIDIA_VISIBLE_DEVICES=all            # Use all available GPUs
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
    restart: unless-stopped                   # Automatically restart unless stopped manually
    # Uncomment the following lines if you're using a custom network
    #networks:
    #  - ai_network

# Uncomment if using a custom network
#networks:
#  ai_network:
#    driver: bridge
